export * from './LandingPage.tsx'
export * from './login-page'
export * from '@components/LandingPage/ui/web/ProfilesSection.tsx'
export * from './ProfileCard'
// export * from './DetailPage/DetailPage.tsx'
// export * from './footer-section'
