name: deploy to vercel

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v4

      - name: 1. mustache
        run: apk add ruby && gem install mustache

      - name: 2. output
        run: sh ./build.sh

      - name: 3. push
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.POOMASI_TESTREPO_ACCOUNT_GH_TOKEN }}
          # SHH Deploy Key로 “output 폴더”를 다른 리포(mobile-test)의 develop 브랜치로 푸쉬하는 역할
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          repository: taetae0707/mobile-test
          source-directory: "output"
          destination-github-username: taetae0707
          destination-repository-name: mobile-test
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop
        env:
          API_TOKEN_GITHUB: ${{ secrets.POOMASI_TESTREPO_ACCOUNT_GH_TOKEN }}
          DEBUG: true

      - name: 디버그: output 디렉토리 목록 출력
        run: ls -al ./output